# Generated by Django 5.2.7 on 2025-11-02 20:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ministry_owner', models.CharField(help_text='Ministry responsible for this program', max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('eligibility_criteria', models.TextField(blank=True)),
                ('estimated_beneficiaries', models.CharField(blank=True, help_text="Estimated number of beneficiaries (e.g., '1.8 million families')", max_length=100)),
                ('max_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Government Program',
                'verbose_name_plural': 'Government Programs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('issuing_authority', models.CharField(max_length=200)),
                ('charity_type', models.CharField(choices=[('HEALTH', 'Health'), ('EDUCATION', 'Education'), ('HOUSING', 'Housing'), ('FOOD', 'Food & Nutrition'), ('SOCIAL', 'Social Services'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('license_certificate', models.FileField(blank=True, null=True, upload_to='charities/licenses/')),
                ('admin_id_document', models.FileField(blank=True, null=True, upload_to='charities/admin_ids/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charity_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Charities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('family_size', models.PositiveIntegerField(default=1)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('special_needs', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_profile', to=settings.AUTH_USER_MODEL)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='main_app.charity')),
            ],
            options={
                'verbose_name_plural': 'Beneficiaries',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('max_capacity', models.PositiveIntegerField()),
                ('current_registrations', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main_app.charity')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('attended', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='main_app.beneficiary')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='main_app.event')),
            ],
            options={
                'ordering': ['-registered_at'],
                'unique_together': {('beneficiary', 'event')},
            },
        ),
        migrations.CreateModel(
            name='ProgramApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20)),
                ('application_data', models.JSONField(default=dict, help_text='Additional application-specific data')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_applications', to='main_app.beneficiary')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main_app.program')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('beneficiary', 'program')},
            },
        ),
    ]
