# Generated by Django 5.2.7 on 2025-11-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='icon_url',
            field=models.URLField(blank=True, help_text='Icon URL or emoji for the program', max_length=500),
        ),
    ]
