# Generated by Django 5.2.7 on 2025-11-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_program_icon_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={},
        ),
        migrations.AlterModelOptions(
            name='charity',
            options={},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eventregistration',
            options={},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={},
        ),
        migrations.AlterModelOptions(
            name='programapplication',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='programapplication',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='event',
            name='current_registrations',
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='national_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='estimated_beneficiaries',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='program',
            name='icon_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='program',
            name='ministry_owner',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='programapplication',
            name='application_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(fields=('beneficiary', 'event'), name='uniq_beneficiary_event'),
        ),
        migrations.AddConstraint(
            model_name='programapplication',
            constraint=models.UniqueConstraint(fields=('beneficiary', 'program'), name='uniq_beneficiary_program'),
        ),
    ]
